services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/rockettrainer
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - BALLCHASING_API_KEY=${BALLCHASING_API_KEY:-}
      - STEAM_API_KEY=${STEAM_API_KEY:-}
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./ml:/app/ml
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery-worker:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/rockettrainer
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - BALLCHASING_API_KEY=${BALLCHASING_API_KEY:-}
      - STEAM_API_KEY=${STEAM_API_KEY:-}
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./ml:/app/ml
    depends_on:
      - db
      - redis
    command: celery -A app.celery_app worker --loglevel=info --queues=replay_processing,ml_training

  celery-flower:
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/rockettrainer
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    command: celery -A app.celery_app flower --port=5555

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_DB=rockettrainer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_STEAM_LOGIN_URL=http://localhost:8000/auth/steam-login
    command: npm start
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
