"""Add coaching insights to matches

Revision ID: a8cd459389e0
Revises: 
Create Date: 2025-09-27 01:58:50.225612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cd459389e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('coaching_insights', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('insights_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'insights_generated_at')
    op.drop_column('matches', 'coaching_insights')
    # ### end Alembic commands ###
